name: narratives
channels:
  - defaults
dependencies:
  - brainiak
  - datalad=0.13.3
  - jupyterlab=2.2.8
  - ipykernel=5.3.4
  - ipython=7.18.1
  - matplotlib=3.3.2
  - natsort=7.0.1
  - nibabel=3.1.1
  - numpy=1.19.1
  - pandas=1.1.1
  - pip=20.2.3
  - scipy=1.5.2
  - seaborn=0.11.0
